export default {
    page: 1,
    results: [
        {
            adult: false,
            backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
            genre_ids: [28, 80, 53],
            id: 385687,
            original_language: "en",
            original_title: "Fast X",
            overview:
                "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
            popularity: 656.594,
            poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
            release_date: "2023-05-17",
            title: "Fast X",
            video: false,
            vote_average: 7.193,
            vote_count: 4537
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [28, 35],
            id: 391559,
            original_language: "en",
            original_title: "Fast",
            overview:
                "A balls to the wall action film about Fast, the fastest person alive, who is also named Fast.",
            popularity: 2.68,
            poster_path: "/p8c0a159yKnpciQCFsR8BaC23po.jpg",
            release_date: "2010-06-24",
            title: "Fast",
            video: false,
            vote_average: 4,
            vote_count: 4
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [53, 18],
            id: 556682,
            original_language: "en",
            original_title: "Fast",
            overview:
                "A former special forces badass is recruited by the DEA to lead a covert black ops team to take down drug dealers that are protected by the CIA.",
            popularity: 2.828,
            poster_path: null,
            release_date: "",
            title: "Fast",
            video: false,
            vote_average: 0,
            vote_count: 0
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [],
            id: 1130892,
            original_language: "en",
            original_title: "Fast",
            overview:
                'A woman signs the verb “fast” in American Sign Language by putting her thumb and index finger together and “zipping” her mouth, which resembles the action of closing one’s mouth to be silent. The speed of the action is slowed down, so the person signs the word "fast" very slowly.',
            popularity: 0.6,
            poster_path: "/3F9HuLEo6t6SG34griZ3oRiVLAC.jpg",
            release_date: "2007-01-01",
            title: "Fast",
            video: false,
            vote_average: 8,
            vote_count: 1
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [10749, 35],
            id: 325334,
            original_language: "fr",
            original_title: "Fast",
            overview:
                "Jean-Louis is an naive, amiable orphan who spent his life with his elderly and very strict grandfather. Jean-Louis was a 25-year old virgin when a free-spirited young Parisian woman was temporarily stranded in his village after a bus broke down. She left him a changed man, and she also left a match book from a fast food restaurant called Fast Burger. Soon after his grandfather passes away, the innocent rube Jean-Louis hops on his bike and embarks upon a quest to Paris to find this enigmatic woman. But he is not prepared for the size of Paris, and instead ends up working at a Fast Burger outlet himself. Jean-Louis is a simple soul and freely expresses himself without guile. For some reason this endears him to the staff and management; soon he has been promoted into the upper echelons of the company. One day he meets a rather ditzy Metro security guard, Henriette, who is also at sea in the big city. The kindred spirits click and a sweet romance ensues.",
            popularity: 2.353,
            poster_path: "/Ai1vJjK5Mv8SEJXbV27h5nP3Azl.jpg",
            release_date: "1995-06-07",
            title: "Fast",
            video: false,
            vote_average: 4.5,
            vote_count: 1
        },
        {
            adult: false,
            backdrop_path: "/uOvcyJ3XmUv4geypGvZBeZEFMO6.jpg",
            genre_ids: [28, 80, 18],
            id: 945937,
            original_language: "en",
            original_title: "Fast Charlie",
            overview:
                "When his aging mob boss is whacked, Charlie Swift, a loyal friend and hired gun, will stop at nothing to destroy the upcoming crew that took him out.",
            popularity: 296.245,
            poster_path: "/3y72ffwYRUPOj4yOQbiTaN897Tm.jpg",
            release_date: "2023-12-08",
            title: "Fast Charlie",
            video: false,
            vote_average: 6.293,
            vote_count: 46
        },
        {
            adult: false,
            backdrop_path: "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
            genre_ids: [28, 12, 35],
            id: 384018,
            original_language: "en",
            original_title: "Fast & Furious Presents: Hobbs & Shaw",
            overview:
                "Ever since US Diplomatic Security Service Agent Hobbs and lawless outcast Shaw first faced off, they just have traded smack talk and body blows. But when cyber-genetically enhanced anarchist Brixton's ruthless actions threaten the future of humanity, they join forces to defeat him.",
            popularity: 134.984,
            poster_path: "/qRyy2UmjC5ur9bDi3kpNNRCc5nc.jpg",
            release_date: "2019-08-01",
            title: "Fast & Furious Presents: Hobbs & Shaw",
            video: false,
            vote_average: 6.87,
            vote_count: 6738
        },
        {
            adult: false,
            backdrop_path: "/AqtTwTPOjRnmSudK1rywiUoE9xH.jpg",
            genre_ids: [35, 10749, 28, 18],
            id: 889741,
            original_language: "th",
            original_title: "เร็วโหด..เหมือนโกรธเธอ",
            overview:
                "When a world champion of sport stacking is dumped by his long-time girlfriend, he has to learn basic adulting skills in order to live alone and take care of himself.",
            popularity: 14.443,
            poster_path: "/46Ab9aS5x9ZVhsbcQ3d5QjzfuBb.jpg",
            release_date: "2022-04-06",
            title: "Fast & Feel Love",
            video: false,
            vote_average: 7.2,
            vote_count: 27
        },
        {
            adult: false,
            backdrop_path: "/nR7e6of0ZVxB8v04gGbjOJ9rb8w.jpg",
            genre_ids: [12, 16, 35, 10751, 14],
            id: 424656,
            original_language: "ja",
            original_title: "クレヨンしんちゃん 爆睡！ユメミーワールド大突撃",
            overview:
                "One night, the Nohara family were enjoying a pleasant dream, when suddenly a big fish appeared in their dreams and ate them. The next morning, Hiroshi read in the newspaper that everybody in another town had the same nightmare as him, but it seemed to have ended. But Hiroshi also heard the same dream from Misae, Shinnosuke, Himawari and even Shiro. They were surprised and thought if the same thing is happening in Kasukabe too. In kindergarten, on telling others about his nightmare, Shinnosuke was surprised to know that everybody too had the same dream. Then a mysterious girl named Saki was transferred to Futaba Kindergarten and joined Shinnosuke's class. Everyone in the class, including the rather inactive Bo-chan, were all excited and happy on seeing her. But Saki had a cold attitude and didn't get along well.",
            popularity: 9.564,
            poster_path: "/obwoDfQFUoZ80xrQXbXLZUBIh6z.jpg",
            release_date: "2016-04-16",
            title: "Crayon Shin-chan: Fast Asleep! Dreaming World Big Assault!",
            video: false,
            vote_average: 7,
            vote_count: 41
        },
        {
            adult: false,
            backdrop_path: "/YBSeCMORtdET4PV1gIJdfPAcHi.jpg",
            genre_ids: [18, 35],
            id: 258322,
            original_language: "it",
            original_title: "Allacciate le cinture",
            overview:
                "Elena and Antonio seem not to be made for each other. They are too different in terms of character, life choices, worldview, and the way they relate to others. They are total opposites. However, they are overwhelmed by a mutual attraction they're trying hard to avoid; but to which they succumb to.",
            popularity: 6.934,
            poster_path: "/8yDZUKQQLZQEPw1wRXS2ZNEsHqG.jpg",
            release_date: "2014-03-06",
            title: "Fasten Your Seatbelts",
            video: false,
            vote_average: 6.8,
            vote_count: 241
        },
        {
            adult: false,
            backdrop_path: "/uTz92k0CfZpn1p3xRmPbgt7MQTz.jpg",
            genre_ids: [35],
            id: 13342,
            original_language: "en",
            original_title: "Fast Times at Ridgemont High",
            overview:
                "Based on the real-life adventures chronicled by Cameron Crowe, Fast Times follows a group of high school students growing up in Southern California. Stacy Hamilton and Mark Ratner are looking for a love interest, and are helped along by their older classmates, Linda Barrett and Mike Damone, respectively. At the center of the film is Jeff Spicoli, a perpetually stoned surfer who faces-off with the resolute Mr. Hand—a man convinced that everyone is on dope.",
            popularity: 37.344,
            poster_path: "/s1DA8H7qwoOcAEhow2rCzuQtpuO.jpg",
            release_date: "1982-08-13",
            title: "Fast Times at Ridgemont High",
            video: false,
            vote_average: 6.797,
            vote_count: 1125
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [28, 80, 53],
            id: 755679,
            original_language: "en",
            original_title: "Fast X: Part 2",
            overview: "The eleventh installment in The Fast Saga.",
            popularity: 72.299,
            poster_path: "/lD8V3DBban95Mxz4sjuA81Tw771.jpg",
            release_date: "2025-04-04",
            title: "Fast X: Part 2",
            video: false,
            vote_average: 0,
            vote_count: 0
        },
        {
            adult: false,
            backdrop_path: "/oooZkKlOCmswD7JKEBG3FbG8pPn.jpg",
            genre_ids: [18, 28, 53],
            id: 375946,
            original_language: "fr",
            original_title: "Le Convoi",
            overview:
                "Málaga, southern Spain. Seven men, divided into four cars, set off with a large drug shipment towards Creil, a city near Paris; a routine mission that will be complicated by a fatal sequence of events.",
            popularity: 8.208,
            poster_path: "/ueJOZdL66KD8An9HntIdxKHxx.jpg",
            release_date: "2016-01-20",
            title: "Fast Convoy",
            video: false,
            vote_average: 5.592,
            vote_count: 103
        },
        {
            adult: false,
            backdrop_path: "/bXILbW1i0WRShd6s4LfLKdJM6zm.jpg",
            genre_ids: [10751, 16, 35, 28, 12],
            id: 42246,
            original_language: "en",
            original_title: "Tom and Jerry: The Fast and the Furry",
            overview:
                'After being evicted from their old house by Tom\'s owner for causing major damage, cat and mouse Tom and Jerry enter a race entitled the "Fabulous Super Race" to win a mansion.',
            popularity: 33.676,
            poster_path: "/4pQhh5bU1KcUeXqPOteWsCkNZPK.jpg",
            release_date: "2005-10-11",
            title: "Tom and Jerry: The Fast and the Furry",
            video: false,
            vote_average: 6.892,
            vote_count: 245
        },
        {
            adult: false,
            backdrop_path: "/vp7ZXmEHxb8rI6LWguqHQzkRJ8L.jpg",
            genre_ids: [35],
            id: 36175,
            original_language: "ja",
            original_title: "亀は意外と速く泳ぐ",
            overview:
                "Suzume Katagura, a bored housewife, spends her days doing chores and taking care of her husband's pet turtle. One day, she sees a wanted ad for spies. Hoping for some excitement in her life, she decides to give them a call.",
            popularity: 7.39,
            poster_path: "/nThjwGHNHKXI7Y1oGdrWzcoAF7P.jpg",
            release_date: "2005-07-02",
            title: "Turtles Are Surprisingly Fast Swimmers",
            video: false,
            vote_average: 6.1,
            vote_count: 28
        },
        {
            adult: false,
            backdrop_path: "/k63u1PAW8aL7hy1Rwtn0d0oy4rn.jpg",
            genre_ids: [18, 12, 36],
            id: 9912,
            original_language: "en",
            original_title: "The World's Fastest Indian",
            overview:
                "The life story of New Zealander Burt Munro, who spent years building a 1920 Indian motorcycle—a bike which helped him set the land-speed world record at Utah's Bonneville Salt Flats in 1967.",
            popularity: 24.609,
            poster_path: "/i7obsEYXjo725H9vneFqxxUiZw7.jpg",
            release_date: "2005-10-12",
            title: "The World's Fastest Indian",
            video: false,
            vote_average: 7.613,
            vote_count: 654
        },
        {
            adult: false,
            backdrop_path: "/gRHRNtiqvn5bBUUIVu09zd8lorW.jpg",
            genre_ids: [80, 18, 28, 53],
            id: 41283,
            original_language: "en",
            original_title: "Faster",
            overview:
                "After 10 years in prison, Driver is now a free man with a single focus - hunting down the people responsible for brutally murdering his brother.",
            popularity: 41.227,
            poster_path: "/AsUeaXrhw4oscCSjUZ6heh1pVvd.jpg",
            release_date: "2010-11-23",
            title: "Faster",
            video: false,
            vote_average: 6.329,
            vote_count: 1771
        },
        {
            adult: false,
            backdrop_path: "/mEMjegjbF08sV7GGvn8nIThp21z.jpg",
            genre_ids: [12, 16],
            id: 51887,
            original_language: "en",
            original_title: "Fast Film",
            overview:
                "Bits of found film and different types of animation illustrate a classic chase scene scenario: A woman is abducted and a man comes to her rescue, but during their escape they find themselves in the enemy's secret headquarters.",
            popularity: 1.761,
            poster_path: "/l72k120RMWPrBvwQYeEV13EqLUi.jpg",
            release_date: "2003-05-01",
            title: "Fast Film",
            video: false,
            vote_average: 6.8,
            vote_count: 33
        },
        {
            adult: false,
            backdrop_path: "/kEYzCALqaU8cMMRPtghjAjcLRQi.jpg",
            genre_ids: [80, 28, 53],
            id: 315,
            original_language: "en",
            original_title: "Faster, Pussycat! Kill! Kill!",
            overview:
                "Three strippers seeking thrills encounter a young couple in the desert. After dispatching the boyfriend, they take the girl hostage and begin scheming on a crippled old man living with his two sons in the desert, reputedly hiding a tidy sum of cash. They become house guests of the old man and try and seduce the sons in an attempt to locate the money, not realizing that the old man has a few sinister intentions of his own.",
            popularity: 17.34,
            poster_path: "/4mld2L1vWqgqFQmKa7KU4HzLKPi.jpg",
            release_date: "1965-08-06",
            title: "Faster, Pussycat! Kill! Kill!",
            video: false,
            vote_average: 6.4,
            vote_count: 288
        },
        {
            adult: false,
            backdrop_path: "/hJRmxf1SHJi3t7l9grvViwPsgAQ.jpg",
            genre_ids: [35],
            id: 253060,
            original_language: "tl",
            original_title: "Kakabakaba Ka Ba?",
            overview:
                "In a spoof on the contemporary sacred cons, two yuppy couples get entangled with warring smugglers of dope that include fake priests and nuns as well as Japanese and Chinese agents.",
            popularity: 3.2,
            poster_path: "/jK9CptmQy7zRvDfSmc8X0XBpUdp.jpg",
            release_date: "1980-08-08",
            title: "Will Your Heart Beat Faster?",
            video: false,
            vote_average: 6.7,
            vote_count: 7
        }
    ],
    total_pages: 33,
    total_results: 642
}
