export default {
    page: 1,
    results: [
        {
            adult: false,
            backdrop_path: "/cpZAXIYA0lkZMpAt7d1MmH8ojNV.jpg",
            genre_ids: [28, 53, 12],
            id: 667,
            original_language: "en",
            original_title: "You Only Live Twice",
            overview:
                "A mysterious spacecraft captures Russian and American space capsules and brings the two superpowers to the brink of war. James Bond investigates the case in Japan and comes face to face with his archenemy Blofeld.",
            popularity: 29.265,
            poster_path: "/fdRbvRcEXcf2rC4ghLFZzCWPSmB.jpg",
            release_date: "1967-06-13",
            title: "You Only Live Twice",
            video: false,
            vote_average: 6.567,
            vote_count: 2002
        },
        {
            adult: false,
            backdrop_path: "/jMBpJFRtrtIXymer93XLavPwI3P.jpg",
            genre_ids: [28, 53, 878],
            id: 679,
            original_language: "en",
            original_title: "Aliens",
            overview:
                "When Ripley's lifepod is found by a salvage crew over 50 years later, she finds that terra-formers are on the very planet they found the alien species. When the company sends a family of colonists out to investigate her story—all contact is lost with the planet and colonists. They enlist Ripley and the colonial marines to return and search for answers.",
            popularity: 80.033,
            poster_path: "/r1x5JGpyqZU8PYhbs4UcrO1Xb6x.jpg",
            release_date: "1986-07-18",
            title: "Aliens",
            video: false,
            vote_average: 7.937,
            vote_count: 8906
        },
        {
            adult: false,
            backdrop_path: "/jeC1kzwWnZTuXl7xF4E5D70BD8c.jpg",
            genre_ids: [12, 878],
            id: 775,
            original_language: "fr",
            original_title: "Le Voyage dans la Lune",
            overview:
                "Professor Barbenfouillis and five of his colleagues from the Academy of Astronomy travel to the Moon aboard a rocket propelled by a giant cannon. Once on the lunar surface, the bold explorers face the many perils hidden in the caves of the mysterious planet.",
            popularity: 23.344,
            poster_path: "/9o0v5LLFk51nyTBHZSre6OB37n2.jpg",
            release_date: "1902-04-17",
            title: "A Trip to the Moon",
            video: false,
            vote_average: 7.942,
            vote_count: 1628
        },
        {
            adult: false,
            backdrop_path: "/5QTwfS9vcr22Nl7PCcUro7dEMFq.jpg",
            genre_ids: [12, 878],
            id: 811,
            original_language: "en",
            original_title: "Silent Running",
            overview:
                "In a future Earth barren of all flora and fauna, the planet's ecosystems exist only in large pods attached to spacecraft. When word comes in that the pods are to be jettisoned into space and destroyed so that the spacecraft can be reused for commercial purposes, most of the crew of the Valley Forge rejoice at the prospect of going home. Not so for botanist Freeman Lowell who loves the forest and its creatures, so decides to take matters into his own hands to protect what he loves.",
            popularity: 22.996,
            poster_path: "/oWLdnBKgVVUd7DougF5pNuIkZZJ.jpg",
            release_date: "1972-03-09",
            title: "Silent Running",
            video: false,
            vote_average: 6.415,
            vote_count: 522
        },
        {
            adult: false,
            backdrop_path: "/9EUmwXS6EbY5djAhLtBGzUbBwNV.jpg",
            genre_ids: [878, 12],
            id: 830,
            original_language: "en",
            original_title: "Forbidden Planet",
            overview:
                "Starship C57D travels to planet Altair 4 in search of the crew of spaceship \"Bellerophon,\" a scientific expedition that has been missing for 20 years, only to find themselves unwelcome by the expedition's lone survivor and warned of destruction by an invisible force if they don't turn back immediately.",
            popularity: 31.63,
            poster_path: "/aq0OQfRS7hDDI8vyD0ICbH9eguC.jpg",
            release_date: "1956-03-23",
            title: "Forbidden Planet",
            video: false,
            vote_average: 7.257,
            vote_count: 851
        },
        {
            adult: false,
            backdrop_path: "/inQQLXDOkb3jwDqNqHF8Lnel6yU.jpg",
            genre_ids: [878, 12],
            id: 831,
            original_language: "en",
            original_title: "This Island Earth",
            overview:
                "Aliens have landed and are hiding on Earth, but need Earth’s scientists to help them fight an inter-planetary war.",
            popularity: 10.486,
            poster_path: "/2viRDpHmhzQoreZok2auLjkVbSE.jpg",
            release_date: "1955-06-01",
            title: "This Island Earth",
            video: false,
            vote_average: 6,
            vote_count: 200
        },
        {
            adult: false,
            backdrop_path: "/5wJ2tckpvwcxGCAgZiccodwEJpf.jpg",
            genre_ids: [28, 878, 12],
            id: 841,
            original_language: "en",
            original_title: "Dune",
            overview:
                "In the year 10,191, the world is at war for control of the desert planet Arrakis—the only place where the space-travel substance Melange 'Spice' can be found. But when one leader gives up control, it's only so he can stage a coup with some unsavory characters.",
            popularity: 46.005,
            poster_path: "/ngUaHgSZGkKy1Izwjk7qwZLOC5A.jpg",
            release_date: "1984-12-14",
            title: "Dune",
            video: false,
            vote_average: 6.203,
            vote_count: 2650
        },
        {
            adult: false,
            backdrop_path: "/aD5z4yRysFl3KLiPOTIMsgvstWT.jpg",
            genre_ids: [28, 12, 14, 878],
            id: 849,
            original_language: "en",
            original_title: "Krull",
            overview:
                "A prince and a fellowship of companions set out to rescue his bride from a fortress of alien invaders who have arrived on their home planet.",
            popularity: 20.854,
            poster_path: "/b1anwwbh00R3iOgM88L5jf7qHBt.jpg",
            release_date: "1983-07-29",
            title: "Krull",
            video: false,
            vote_average: 6.026,
            vote_count: 497
        },
        {
            adult: false,
            backdrop_path: "/4OzWF8mXU9BP8Y4qGFcLl8d0Dr4.jpg",
            genre_ids: [28, 12, 878],
            id: 861,
            original_language: "en",
            original_title: "Total Recall",
            overview:
                "Construction worker Douglas Quaid's obsession with the planet Mars leads him to visit Recall, a company who manufacture memories. Something goes wrong during his memory implant turning Doug's life upside down and even to question what is reality and what isn't.",
            popularity: 48.203,
            poster_path: "/wVbeL6fkbTKSmNfalj4VoAUUqJv.jpg",
            release_date: "1990-06-01",
            title: "Total Recall",
            video: false,
            vote_average: 7.29,
            vote_count: 5344
        },
        {
            adult: false,
            backdrop_path: "/8zvo2J1rKbzcfxaX9lHRgHgOEf0.jpg",
            genre_ids: [53, 878],
            id: 4437,
            original_language: "en",
            original_title: "2010",
            overview:
                "While planet Earth poises on the brink of nuclear self-destruction, a team of Russian and American scientists aboard the Leonov hurtles to a rendezvous with the still-orbiting Discovery spacecraft and its sole known survivor, the homicidal computer HAL.",
            popularity: 21.368,
            poster_path: "/mEWKXuCMv7mFMxXVSTI3v8UOQuq.jpg",
            release_date: "1984-12-06",
            title: "2010",
            video: false,
            vote_average: 6.6,
            vote_count: 849
        },
        {
            adult: false,
            backdrop_path: "/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg",
            genre_ids: [28, 12, 14],
            id: 791373,
            original_language: "en",
            original_title: "Zack Snyder's Justice League",
            overview:
                "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
            popularity: 138.579,
            poster_path: "/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
            release_date: "2021-03-18",
            title: "Zack Snyder's Justice League",
            video: false,
            vote_average: 8.183,
            vote_count: 9412
        },
        {
            adult: false,
            backdrop_path: "/tE7jQPtH6VCQC1AmzfOcgSmiMiI.jpg",
            genre_ids: [28],
            id: 9569,
            original_language: "en",
            original_title: "Hard to Kill",
            overview:
                "Mason Storm, a 'go it alone' cop, is gunned down at home. The intruders kill his wife, and think they've killed both Mason and his son too. Mason is secretly taken to a hospital where he spends several years in a coma. His son meanwhile is growing up thinking his father is dead. When Mason wakes up, everyone is in danger - himself, his son, his best friend, his nurse - but most of all those who arranged for his death",
            popularity: 23.167,
            poster_path: "/nmtMNxslljllSTVtt7VIOXdxSZp.jpg",
            release_date: "1990-02-09",
            title: "Hard to Kill",
            video: false,
            vote_average: 5.982,
            vote_count: 558
        },
        {
            adult: false,
            backdrop_path: "/bumIpNTKmLY380bruTgIDTrXfpZ.jpg",
            genre_ids: [12, 14, 28, 35, 10751],
            id: 9593,
            original_language: "en",
            original_title: "Last Action Hero",
            overview:
                "Following the death of his father, young Danny Madigan takes comfort in watching action movies featuring the indestructible Los Angeles cop Jack Slater. After being given a magic ticket by theater manager Nick, Danny is sucked into the screen and bonds with Slater. When evil fictional villain Benedict gets his hands on the ticket and enters the real world, Danny and Jack must follow and stop him.",
            popularity: 25.914,
            poster_path: "/yTfjHPqh7C7bkfMtEKx2mPdorQw.jpg",
            release_date: "1993-06-18",
            title: "Last Action Hero",
            video: false,
            vote_average: 6.431,
            vote_count: 2496
        },
        {
            adult: false,
            backdrop_path: "/sAbP0xIjPCbf3OdqzdD3BnlHJ3x.jpg",
            genre_ids: [53, 28, 80, 18],
            id: 9594,
            original_language: "en",
            original_title: "Double Impact",
            overview:
                "Jean Claude Van Damme plays a dual role as Alex and Chad, twins separated at the death of their parents. Chad is raised by a family retainer in Paris, Alex becomes a petty crook in Hong Kong. Seeing a picture of Alex, Chad rejoins him and convinces him that his rival in Hong Kong is also the man who killed their parents. Alex is suspicious of Chad, especially when it comes to his girlfriend.",
            popularity: 33.581,
            poster_path: "/tmzwvSqoMC37Tgqwj4mA2dHNSmw.jpg",
            release_date: "1991-07-31",
            title: "Double Impact",
            video: false,
            vote_average: 6.093,
            vote_count: 959
        },
        {
            adult: false,
            backdrop_path: "/soayFfANJdm3ykSQO71d6hAuMDR.jpg",
            genre_ids: [12, 14, 28],
            id: 9610,
            original_language: "en",
            original_title: "Conan the Destroyer",
            overview:
                "Conan is commissioned by the evil queen Taramis to safely escort a teen princess and her powerful bodyguard to a far away castle to retrieve the magic Horn of Dagoth. Unknown to Conan, the queen plans to sacrifice the princess when she returns and inherit her kingdom after the bodyguard kills Conan. The queen's plans fail to take into consideration Conan's strength and cunning and the abilities of his sidekicks: the eccentric wizard Akiro, the warrior woman Zula, and the inept Malak. Together the hero and his allies must defeat both mortal and supernatural foes in this voyage to sword-and-sorcery land.",
            popularity: 28.743,
            poster_path: "/m5i7S46DT1ESy7URkh2l92awGRr.jpg",
            release_date: "1984-06-29",
            title: "Conan the Destroyer",
            video: false,
            vote_average: 6.1,
            vote_count: 1370
        },
        {
            adult: false,
            backdrop_path: "/wz9Fntmcqvrd4bqtPCTLp5DeEwc.jpg",
            genre_ids: [28, 35],
            id: 10117,
            original_language: "en",
            original_title: "Action Jackson",
            overview:
                "Vengeance drives a tough Detroit cop to stay on the trail of a power hungry auto magnate who's systematically eliminating his competition.",
            popularity: 14.196,
            poster_path: "/8zVlaDYmygJ29LlKyTn7bqm22pT.jpg",
            release_date: "1988-02-12",
            title: "Action Jackson",
            video: false,
            vote_average: 5.512,
            vote_count: 211
        },
        {
            adult: false,
            backdrop_path: "/tSlyLIEAO5cEp9DYV6wYY1e2Jgz.jpg",
            genre_ids: [878, 28, 53, 12],
            id: 10134,
            original_language: "en",
            original_title: "Cyborg",
            overview:
                "A martial artist hunts a killer in a plague-infested urban dump of the future.",
            popularity: 19.666,
            poster_path: "/nOspcG8HP6KPdMvzezavRbzYCEw.jpg",
            release_date: "1989-04-07",
            title: "Cyborg",
            video: false,
            vote_average: 5.635,
            vote_count: 646
        },
        {
            adult: false,
            backdrop_path: "/zW1qfxsc3xEV4GHGGyFiesYuxAj.jpg",
            genre_ids: [80, 28, 53],
            id: 10167,
            original_language: "en",
            original_title: "Half Past Dead",
            overview:
                "A man goes undercover in a hi-tech prison to find out information to help prosecute those who killed his wife. While there, he stumbles onto a plot involving a death-row inmate and his $200 million stash of gold.",
            popularity: 13.163,
            poster_path: "/fJhudecoqyoZLoCwAZvqNPd7MK5.jpg",
            release_date: "2002-11-15",
            title: "Half Past Dead",
            video: false,
            vote_average: 5.2,
            vote_count: 327
        },
        {
            adult: false,
            backdrop_path: "/3QtpB5RxBcz385UHN6IxjJXVBvG.jpg",
            genre_ids: [878, 28, 12, 35],
            id: 10179,
            original_language: "en",
            original_title: "The Ice Pirates",
            overview:
                "In the not too distant future, where by far the most precious commodity in the galaxy is water. The last surviving water planet was somehow removed to the unreachable centre of the galaxy at the end of the galactic trade wars. The galaxy is ruled by an evil emperor presiding over a trade oligarchy that controls all mining and sale of ice from asteroids and comets.",
            popularity: 14.665,
            poster_path: "/tv2iZbQYWwKcWOUWVFxOhcchKZT.jpg",
            release_date: "1984-03-16",
            title: "The Ice Pirates",
            video: false,
            vote_average: 5.638,
            vote_count: 160
        },
        {
            adult: false,
            backdrop_path: "/qvWptvV5PEqEGrls5JmgKXiJ0UU.jpg",
            genre_ids: [28, 53, 18],
            id: 10222,
            original_language: "en",
            original_title: "Kickboxer",
            overview:
                "If your enemy refuses to be humbled... Destroy him. Accompanied by his brother Kurt (Van Damme), American kickboxing champion Eric Sloane (Dennis Alexio), arrives in Thailand to defeat the Eastern warriors at their own sport. His opponent: ruthless fighter and Thai champion, Tong Po. Tong not only defeats Eric, he paralyzes him for life. Crazed with anger, Kurt vows revenge.",
            popularity: 19.656,
            poster_path: "/eP1GzZxRL7VpIEpeawtAjlYhNQj.jpg",
            release_date: "1989-04-20",
            title: "Kickboxer",
            video: false,
            vote_average: 6.766,
            vote_count: 1270
        }
    ],
    total_pages: 3468,
    total_results: 69344
}
