export default {
    page: 1,
    results: [
        {
            adult: false,
            backdrop_path: "/sRLC052ieEzkQs9dEtPMfFxYkej.jpg",
            id: 848326,
            title: "Rebel Moon - Part One: A Child of Fire",
            original_language: "en",
            original_title: "Rebel Moon - Part One: A Child of Fire",
            overview:
                "When a peaceful colony on the edge of the galaxy finds itself threatened by the armies of the tyrannical Regent Balisarius, they dispatch Kora, a young woman with a mysterious past, to seek out warriors from neighboring planets to help them take a stand.",
            poster_path: "/ui4DrH1cKk2vkHshcUcGt2lKxCm.jpg",
            media_type: "movie",
            genre_ids: [878, 28, 12],
            popularity: 923.889,
            release_date: "2023-12-15",
            video: false,
            vote_average: 6.462,
            vote_count: 496
        },
        {
            adult: false,
            backdrop_path: "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
            id: 572802,
            title: "Aquaman and the Lost Kingdom",
            original_language: "en",
            original_title: "Aquaman and the Lost Kingdom",
            overview:
                "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
            poster_path: "/8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg",
            media_type: "movie",
            genre_ids: [28, 12, 14],
            popularity: 1999.169,
            release_date: "2023-12-20",
            video: false,
            vote_average: 6.542,
            vote_count: 190
        },
        {
            adult: false,
            backdrop_path: "/ipmUfBf3RxIdATbYI4CcPlnTsWs.jpg",
            id: 930564,
            title: "Saltburn",
            original_language: "en",
            original_title: "Saltburn",
            overview:
                "Struggling to find his place at Oxford University, student Oliver Quick finds himself drawn into the world of the charming and aristocratic Felix Catton, who invites him to Saltburn, his eccentric family's sprawling estate, for a summer never to be forgotten.",
            poster_path: "/qjhahNLSZ705B5JP92YMEYPocPz.jpg",
            media_type: "movie",
            genre_ids: [18, 35, 53],
            popularity: 375.845,
            release_date: "2023-11-16",
            video: false,
            vote_average: 7.223,
            vote_count: 224
        },
        {
            adult: false,
            backdrop_path: "/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg",
            id: 695721,
            title: "The Hunger Games: The Ballad of Songbirds & Snakes",
            original_language: "en",
            original_title: "The Hunger Games: The Ballad of Songbirds & Snakes",
            overview:
                "64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.",
            poster_path: "/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg",
            media_type: "movie",
            genre_ids: [18, 878, 28],
            popularity: 3233.513,
            release_date: "2023-11-15",
            video: false,
            vote_average: 7.219,
            vote_count: 1040
        },
        {
            adult: false,
            backdrop_path: "/ktHEdqmMWC1wdfPRMRCTZe2OISL.jpg",
            id: 1071215,
            title: "Thanksgiving",
            original_language: "en",
            original_title: "Thanksgiving",
            overview:
                "After a Black Friday riot ends in tragedy, a mysterious Thanksgiving-inspired killer terrorizes Plymouth, Massachusetts - the birthplace of the holiday. Picking off residents one by one, what begins as random revenge killings are soon revealed to be part of a larger, sinister holiday plan.",
            poster_path: "/f5f3TEVst1nHHyqgn7Z3tlwnBIH.jpg",
            media_type: "movie",
            genre_ids: [27, 53, 9648],
            popularity: 1126.478,
            release_date: "2023-11-16",
            video: false,
            vote_average: 6.648,
            vote_count: 287
        },
        {
            adult: false,
            backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
            id: 872585,
            title: "Oppenheimer",
            original_language: "en",
            original_title: "Oppenheimer",
            overview:
                "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
            poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
            media_type: "movie",
            genre_ids: [18, 36],
            popularity: 752.689,
            release_date: "2023-07-19",
            video: false,
            vote_average: 8.1,
            vote_count: 5624
        },
        {
            adult: false,
            backdrop_path: "/rmfIhftLXpHEZzkLSpWQMZhirMJ.jpg",
            id: 823482,
            title: "Dream Scenario",
            original_language: "en",
            original_title: "Dream Scenario",
            overview:
                "Hapless family man Paul Matthews finds his life turned upside down when millions of strangers suddenly start seeing him in their dreams. But when his nighttime appearances take a nightmarish turn, Paul is forced to navigate his newfound stardom.",
            poster_path: "/zhEaG0KQ32KerHEWmImsYLexDix.jpg",
            media_type: "movie",
            genre_ids: [35, 14],
            popularity: 170.52,
            release_date: "2023-11-10",
            video: false,
            vote_average: 7.167,
            vote_count: 108
        },
        {
            adult: false,
            backdrop_path: "/et0G74BxoBgNQEZBkUcVhsgeRFF.jpg",
            id: 523607,
            title: "Maestro",
            original_language: "en",
            original_title: "Maestro",
            overview:
                "A towering and fearless love story chronicling the lifelong relationship between Leonard Bernstein and Felicia Montealegre Cohn Bernstein. A love letter to life and art, Maestro at its core is an emotionally epic portrayal of family and love.",
            poster_path: "/kxj7rMco6RNYsVcNwuGAIlfWu64.jpg",
            media_type: "movie",
            genre_ids: [18, 10749, 10402],
            popularity: 203.126,
            release_date: "2023-11-22",
            video: false,
            vote_average: 6.662,
            vote_count: 136
        },
        {
            adult: false,
            backdrop_path: "/kbxWL3hsZVmNZ1v7FVqpPWaWOZA.jpg",
            id: 1211199,
            title: "Thank You, I'm Sorry",
            original_language: "sv",
            original_title: "Tack och förlåt",
            overview:
                "Suddenly alone during the late stages of her pregnancy, Sara receives an unexpected lifeline when Linda, her estranged older sister, arrives.",
            poster_path: "/uGnFNjzi1hXZ7CiywbOERUh1KAE.jpg",
            media_type: "movie",
            genre_ids: [35, 18],
            popularity: 25.766,
            release_date: "2023-12-26",
            video: false,
            vote_average: 7,
            vote_count: 1
        },
        {
            adult: false,
            backdrop_path: "/xJdVOpzJ4SOV8yJQpaIXByZOFh1.jpg",
            id: 1211419,
            title: "A Vampire in the Family",
            original_language: "pt",
            original_title: "Meu cunhado é um vampiro",
            overview:
                "Fernandinho is a family man, former football player and a current podcast commentator that is surprised by the visit of his inconvenient brother-in-law, Gregorio, who discovers to be lazy and literally a bloodsucker - a vampire.",
            poster_path: "/wM0kMyH7YIWm8UFfnJnCyij0XUu.jpg",
            media_type: "movie",
            genre_ids: [35, 27],
            popularity: 48.887,
            release_date: "2023-12-23",
            video: false,
            vote_average: 5.188,
            vote_count: 8
        },
        {
            adult: false,
            backdrop_path: "/r9oTasGQofvkQY5vlUXglneF64Z.jpg",
            id: 1029575,
            title: "The Family Plan",
            original_language: "en",
            original_title: "The Family Plan",
            overview:
                "Dan Morgan is many things: a devoted husband, a loving father, a celebrated car salesman. He's also a former assassin. And when his past catches up to his present, he's forced to take his unsuspecting family on a road trip unlike any other.",
            poster_path: "/jLLtx3nTRSLGPAKl4RoIv1FbEBr.jpg",
            media_type: "movie",
            genre_ids: [28, 35],
            popularity: 1564.216,
            release_date: "2023-12-14",
            video: false,
            vote_average: 7.429,
            vote_count: 372
        },
        {
            adult: false,
            backdrop_path: "/nHf61UzkfFno5X1ofIhugCPus2R.jpg",
            id: 346698,
            title: "Barbie",
            original_language: "en",
            original_title: "Barbie",
            overview:
                "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
            poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
            media_type: "movie",
            genre_ids: [35, 12, 14],
            popularity: 419.27,
            release_date: "2023-07-19",
            video: false,
            vote_average: 7.167,
            vote_count: 6470
        },
        {
            adult: false,
            backdrop_path: "/yOm993lsJyPmBodlYjgpPwBjXP9.jpg",
            id: 787699,
            title: "Wonka",
            original_language: "en",
            original_title: "Wonka",
            overview:
                "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
            poster_path: "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
            media_type: "movie",
            genre_ids: [35, 10751, 14],
            popularity: 1102.163,
            release_date: "2023-12-06",
            video: false,
            vote_average: 7.185,
            vote_count: 561
        },
        {
            adult: false,
            backdrop_path: "/gg4zZoTggZmpAQ32qIrP5dtnkEZ.jpg",
            id: 891699,
            title: "Silent Night",
            original_language: "en",
            original_title: "Silent Night",
            overview:
                "A tormented father witnesses his young son die when caught in a gang's crossfire on Christmas Eve. While recovering from a wound that costs him his voice, he makes vengeance his life's mission and embarks on a punishing training regimen in order to avenge his son's death.",
            poster_path: "/tlcuhdNMKNGEVpGqBZrAaOOf1A6.jpg",
            media_type: "movie",
            genre_ids: [28, 80],
            popularity: 1329.943,
            release_date: "2023-11-30",
            video: false,
            vote_average: 5.824,
            vote_count: 139
        },
        {
            adult: false,
            backdrop_path: "/1X7vow16X7CnCoexXh4H4F2yDJv.jpg",
            id: 466420,
            title: "Killers of the Flower Moon",
            original_language: "en",
            original_title: "Killers of the Flower Moon",
            overview:
                "When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.",
            poster_path: "/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
            media_type: "movie",
            genre_ids: [80, 18, 36],
            popularity: 770.179,
            release_date: "2023-10-18",
            video: false,
            vote_average: 7.561,
            vote_count: 1589
        },
        {
            adult: false,
            backdrop_path: "/kjQBrc00fB2RjHZB3PGR4w9ibpz.jpg",
            id: 670292,
            title: "The Creator",
            original_language: "en",
            original_title: "The Creator",
            overview:
                "Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.",
            poster_path: "/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg",
            media_type: "movie",
            genre_ids: [28, 12, 18],
            popularity: 660.289,
            release_date: "2023-09-27",
            video: false,
            vote_average: 7.1,
            vote_count: 1578
        },
        {
            adult: false,
            backdrop_path: "/6uLhSLXzB1ooJ3522ydrBZ2Hh0W.jpg",
            id: 771,
            title: "Home Alone",
            original_language: "en",
            original_title: "Home Alone",
            overview:
                "Eight-year-old Kevin McCallister makes the most of the situation after his family unwittingly leaves him behind when they go on Christmas vacation. But when a pair of bungling burglars set their sights on Kevin's house, the plucky kid stands ready to defend his territory. By planting booby traps galore, adorably mischievous Kevin stands his ground as his frantic mother attempts to race home before Christmas Day.",
            poster_path: "/9wSbe4CwObACCQvaUVhWQyLR5Vz.jpg",
            media_type: "movie",
            genre_ids: [35, 10751],
            popularity: 35.564,
            release_date: "1990-11-16",
            video: false,
            vote_average: 7.4,
            vote_count: 10474
        },
        {
            adult: false,
            backdrop_path: "/tLsc8SCFO0rMVgVyNm9XtfnyX84.jpg",
            id: 726209,
            title: "Leave the World Behind",
            original_language: "en",
            original_title: "Leave the World Behind",
            overview:
                "A family's getaway to a luxurious rental home takes an ominous turn when a cyberattack knocks out their devices—and two strangers appear at their door.",
            poster_path: "/29rhl1xopxA7JlGVVsf1UHfYPvN.jpg",
            media_type: "movie",
            genre_ids: [18, 9648, 53, 878],
            popularity: 504.757,
            release_date: "2023-11-22",
            video: false,
            vote_average: 6.534,
            vote_count: 1130
        },
        {
            adult: false,
            backdrop_path: "/9jPoyxjiEYPylUIMI3Ntixf8z3M.jpg",
            id: 520758,
            title: "Chicken Run: Dawn of the Nugget",
            original_language: "en",
            original_title: "Chicken Run: Dawn of the Nugget",
            overview:
                "A band of fearless chickens flock together to save poultry-kind from an unsettling new threat: a nearby farm that's cooking up something suspicious.",
            poster_path: "/exNtEY8QUuQh9e23wSQjkPxKIU3.jpg",
            media_type: "movie",
            genre_ids: [16, 12, 35, 10751],
            popularity: 844.013,
            release_date: "2023-12-08",
            video: false,
            vote_average: 7.527,
            vote_count: 273
        },
        {
            adult: false,
            backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
            id: 569094,
            title: "Spider-Man: Across the Spider-Verse",
            original_language: "en",
            original_title: "Spider-Man: Across the Spider-Verse",
            overview:
                "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
            poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
            media_type: "movie",
            genre_ids: [16, 28, 12, 878],
            popularity: 354.294,
            release_date: "2023-05-31",
            video: false,
            vote_average: 8.4,
            vote_count: 5274
        }
    ],
    total_pages: 1000,
    total_results: 20000
}
