export default {
    page: 1,
    results: [
        {
            adult: false,
            backdrop_path: "/fqAaKOgE0nWDBYgKy7DrQ5vcp7Q.jpg",
            genre_ids: [18, 80, 9648],
            id: 996,
            origin_country: ["US"],
            original_language: "en",
            original_name: "Spenser: For Hire",
            overview:
                'Mystery and suspense series based on Robert Parker\'s "Spenser" novels. Spenser, a private investigator living in Boston, gets involved in a new murder mystery each episode.',
            popularity: 425.83,
            poster_path: "/8n4O7Reyk5es5iyzQk7zfNvuMJ9.jpg",
            first_air_date: "1985-09-20",
            name: "Spenser: For Hire",
            vote_average: 6.8,
            vote_count: 26
        },
        {
            adult: false,
            backdrop_path: "/e9TEzifl1YMTuzB6HmVAUlWDb4d.jpg",
            genre_ids: [18, 80],
            id: 70773,
            origin_country: ["PL"],
            original_language: "pl",
            original_name: "Belle Epoque",
            overview:
                "Krakow, 1908. Jan Edigey-Korycki is employed by the police department to solve murder cases. He is also investigating a fatal duel in which he supposedly killed a man ten years earlier.",
            popularity: 10.318,
            poster_path: "/AuPsEgNCrI7zoiQVg5wsNu3QjYF.jpg",
            first_air_date: "2017-02-15",
            name: "Belle Epoque",
            vote_average: 4.5,
            vote_count: 6
        },
        {
            adult: false,
            backdrop_path: "/dS41b4BOceYXNMkZPJJFA3DBN2G.jpg",
            genre_ids: [80, 35, 10759],
            id: 121500,
            origin_country: ["CA"],
            original_language: "fr",
            original_name: "Les aventures tumultueuses de Jack Carter",
            overview:
                "Private detective Jack Carter is nothing if not eccentric: penniless, he lives, eats and sleeps at the office. When it comes to work, he accepts only those rare cases that intrigue him and leave other detectives mystified. No investigation is too strange or unusual to dishearten Carter.",
            popularity: 2.675,
            poster_path: null,
            first_air_date: "2003-09-08",
            name: "The Tumultuous Adventures of Jack Carter",
            vote_average: 0,
            vote_count: 0
        },
        {
            adult: false,
            backdrop_path: "/wofevfOdZrHPqFnhZTkHHV25IOO.jpg",
            genre_ids: [80, 18, 9648],
            id: 587,
            origin_country: ["US"],
            original_language: "en",
            original_name: "Barnaby Jones",
            overview:
                'Barnaby Jones is a television detective series starring Buddy Ebsen and Lee Meriwether as father- and daughter-in-law who run a private detective firm in Los Angeles. The show ran on CBS from January 28, 1973 to April 3, 1980, beginning as a midseason replacement. William Conrad guest starred as Frank Cannon of Cannon on the first episode of Barnaby Jones, "Requiem for a Son" and the two series had a two-part crossover episode in 1975, "The Deadly Conspiracy".',
            popularity: 862.232,
            poster_path: "/wn1kkCGHJcUQ7C8umfQH9LL2zXR.jpg",
            first_air_date: "1973-01-28",
            name: "Barnaby Jones",
            vote_average: 7.35,
            vote_count: 20
        },
        {
            adult: false,
            backdrop_path: "/jB3CQHS4zBzD00yZG936WmsH6P4.jpg",
            genre_ids: [80, 18, 9648],
            id: 790,
            origin_country: ["GB"],
            original_language: "en",
            original_name: "Agatha Christie's Poirot",
            overview:
                "From England to Egypt, accompanied by his elegant and trustworthy sidekicks, the intelligent yet eccentrically-refined Belgian detective Hercule Poirot pits his wits against a collection of first class deceptions.",
            popularity: 859.499,
            poster_path: "/6f4IVfbn8knb7RjdZlGLuW5guDc.jpg",
            first_air_date: "1989-01-08",
            name: "Agatha Christie's Poirot",
            vote_average: 8.146,
            vote_count: 408
        },
        {
            adult: false,
            backdrop_path: "/fnArp9iDW0mM5Hu6JbIUlVuHRGj.jpg",
            genre_ids: [80, 18, 9648],
            id: 799,
            origin_country: ["GB"],
            original_language: "en",
            original_name: "Sherlock Holmes",
            overview:
                "Sherlock Holmes uses his abilities to take on cases by private clients and those that the Scotland Yard are unable to solve, along with his friend Dr. Watson.",
            popularity: 241.199,
            poster_path: "/thC0OuUvfGbOcoJ3aY5L4vlO6lA.jpg",
            first_air_date: "1984-04-24",
            name: "Sherlock Holmes",
            vote_average: 8.073,
            vote_count: 193
        },
        {
            adult: false,
            backdrop_path: "/bvBlKXI1qP3t461WNXTE9DaZ52J.jpg",
            genre_ids: [35, 10765, 80],
            id: 892,
            origin_country: ["GB"],
            original_language: "en",
            original_name: "Randall and Hopkirk (Deceased)",
            overview:
                "Randall and Hopkirk (Deceased) is a British private detective television series. In the initial episode Hopkirk is murdered during an investigation, but returns as a ghost. Randall is the only main character able to see or hear him, although certain minor characters are also able to do so in various circumstances throughout the series.",
            popularity: 53.729,
            poster_path: "/zHTw4z6IMiSRxJCcDNCUFuVY1Cw.jpg",
            first_air_date: "1969-09-21",
            name: "Randall and Hopkirk (Deceased)",
            vote_average: 7.2,
            vote_count: 10
        },
        {
            adult: false,
            backdrop_path: "/5FrnNiMyQIKeSYRD4hR5b0uRaTF.jpg",
            genre_ids: [80, 18, 9648],
            id: 925,
            origin_country: ["US"],
            original_language: "en",
            original_name: "77 Sunset Strip",
            overview:
                "Stu Bailey and Jeff Spencer are the wisecracking, womanizing private-detective heroes of this Warner Brothers drama. They work out of an office located at 77 Sunset Strip in Los Angeles, California, right next door to a snazzy restaurant where Kookie works as a valet. The finger-snapping, slang-talking Kookie occasionally helps Stu and Jeff with their cases, and eventually becomes a full-fledged member of the detective agency. Rex Randolph and J.R. Hale also join the firm, and Suzanne is their leggy secretary.",
            popularity: 158.273,
            poster_path: "/uoBZjwv3TPJ7L6ybHlUSZvOhodE.jpg",
            first_air_date: "1958-10-10",
            name: "77 Sunset Strip",
            vote_average: 7.05,
            vote_count: 20
        },
        {
            adult: false,
            backdrop_path: "/gyWG3O7yFEXxDW8wGnJvaWVxhS.jpg",
            genre_ids: [80, 18, 9648],
            id: 954,
            origin_country: ["US"],
            original_language: "en",
            original_name: "The Rockford Files",
            overview:
                "Cranky but likable L.A. PI Jim Rockford pulls no punches (but takes plenty of them). An ex-con sent to the slammer for a crime he didn't commit, Rockford takes on cases others don't want, aided by his tough old man, his lawyer girlfriend and some shady associates from his past.",
            popularity: 1525.734,
            poster_path: "/fniHEsTeqHMg41GlCYJxZVgtn7H.jpg",
            first_air_date: "1974-09-13",
            name: "The Rockford Files",
            vote_average: 7.6,
            vote_count: 86
        },
        {
            adult: false,
            backdrop_path: "/kJybNbaMQwCZi7u8UBueN6OzFvh.jpg",
            genre_ids: [80, 18, 9648],
            id: 220074,
            origin_country: ["KR"],
            original_language: "ko",
            original_name: "재벌X형사",
            overview:
                "A childish third-generation tycoon becomes a detective in the violent crime team.",
            popularity: 19.505,
            poster_path: "/xzIZCxZ4blLKnrvxuj0MqFdowx6.jpg",
            first_air_date: "2024-01-26",
            name: "Flex X Cop",
            vote_average: 0,
            vote_count: 0
        },
        {
            adult: false,
            backdrop_path: "/wtYUaMLKIr3eoR5UAbf3C1MiZF6.jpg",
            genre_ids: [80, 18, 9648],
            id: 1340,
            origin_country: ["US"],
            original_language: "en",
            original_name: "Banacek",
            overview:
                "Banacek is an American detective TV series starring George Peppard that aired on the NBC network from 1972 to 1974. The series was part of the rotating NBC Wednesday Mystery Movie anthology. It alternated in its time slot with several other shows but was the only one to last beyond its first season.",
            popularity: 283.423,
            poster_path: "/5Z98mt03uftItoIS91mu0ITxevF.jpg",
            first_air_date: "1972-09-13",
            name: "Banacek",
            vote_average: 8.6,
            vote_count: 17
        },
        {
            adult: false,
            backdrop_path: "/zMs7Jy5ynuVt0I6cag3bjlAhqwH.jpg",
            genre_ids: [16, 35, 10762, 9648],
            id: 96518,
            origin_country: ["US"],
            original_language: "en",
            original_name: "Undercover Elephant",
            overview: "",
            popularity: 3.307,
            poster_path: "/zZdUq6V6RtMagkLPt8KZ2Q4Bzbs.jpg",
            first_air_date: "1977-09-10",
            name: "Undercover Elephant",
            vote_average: 0,
            vote_count: 0
        },
        {
            adult: false,
            backdrop_path: "/4M1EOeMLHxgOgCF8uBBheZIBDLW.jpg",
            genre_ids: [18, 80, 9648],
            id: 1937,
            origin_country: ["US"],
            original_language: "en",
            original_name: "Baywatch Nights",
            overview:
                "Baywatch Nights is an American police and science fiction drama series that aired in syndication from 1995 to 1997. Created by Douglas Schwartz, David Hasselhoff, and Gregory J. Bonann, the series is a spin-off from the popular television series, Baywatch.",
            popularity: 299.073,
            poster_path: "/3UVQpYZ65r855CttLRCov8SKqBB.jpg",
            first_air_date: "1995-09-30",
            name: "Baywatch Nights",
            vote_average: 5.905,
            vote_count: 21
        },
        {
            adult: false,
            backdrop_path: "/mSn5IrrLB6drP1gfwydYAakZG7Y.jpg",
            genre_ids: [35, 18, 9648, 80],
            id: 1998,
            origin_country: ["US"],
            original_language: "en",
            original_name: "Moonlighting",
            overview:
                "After being duped and going bankrupt, model Maddie is convinced by David to become a partner in a detective agency. Together they solve various cases, while getting comfortable with each other.",
            popularity: 283.401,
            poster_path: "/lrx6v9iD7WWkzkYMCvikvG3DIFp.jpg",
            first_air_date: "1985-03-03",
            name: "Moonlighting",
            vote_average: 7.5,
            vote_count: 301
        },
        {
            adult: false,
            backdrop_path: "/gTl1RqyJKXbyUTeyGhMb2dGWoGl.jpg",
            genre_ids: [18, 80, 9648],
            id: 71769,
            origin_country: ["US"],
            original_language: "en",
            original_name: "The Alienist",
            overview:
                "New York, 1896. Police commissioner Theodore Roosevelt brings together criminal psychologist Dr. Laszlo Kreizler, newspaper illustrator John Moore and secretary Sara Howard to investigate several murders of male prostitutes.",
            popularity: 294.711,
            poster_path: "/1qzuS7b2XjiVcWwmDkOyE5hIxUM.jpg",
            first_air_date: "2018-01-22",
            name: "The Alienist",
            vote_average: 7.595,
            vote_count: 519
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [18, 80],
            id: 26529,
            origin_country: ["US"],
            original_language: "en",
            original_name: "Archer",
            overview:
                "Archer is a short-lived American crime drama series starring Brian Keith and John P. Ryan that aired on NBC in 1975.",
            popularity: 7.477,
            poster_path: null,
            first_air_date: "1975-01-30",
            name: "Archer",
            vote_average: 7.5,
            vote_count: 2
        },
        {
            adult: false,
            backdrop_path: "/rAuQB909278cC2rRoTebhrhFSRY.jpg",
            genre_ids: [35, 80, 18, 9648],
            id: 1695,
            origin_country: ["US"],
            original_language: "en",
            original_name: "Monk",
            overview:
                "Adrian Monk was once a rising star with the San Francisco Police Department, legendary for using unconventional means to solve the department's most baffling cases. But after the tragic (and still unsolved) murder of his wife Trudy, he developed an extreme case of obsessive-compulsive disorder. Now working as a private consultant, Monk continues to investigate cases in the most unconventional ways.",
            popularity: 831.179,
            poster_path: "/3axGMbUecXXOPSeG47v2i9wK5y5.jpg",
            first_air_date: "2002-07-12",
            name: "Monk",
            vote_average: 7.9,
            vote_count: 920
        },
        {
            adult: false,
            backdrop_path: "/zUemsKrdb699qVMvfRq8fk39wSb.jpg",
            genre_ids: [18, 80, 9648],
            id: 72736,
            origin_country: ["CA"],
            original_language: "en",
            original_name: "Frankie Drake Mysteries",
            overview:
                "Toronto’s only female private detective in the 1920s takes on the cases the police don’t want or can’t handle. From airplanes and booze running to American G-men, Communists and union busters, Frankie’s fearless sense of adventure gets her into all kinds of trouble, but she always manages to find her way out.",
            popularity: 212.8,
            poster_path: "/saTRepmDwP3df0f0E8tJNX4BnrS.jpg",
            first_air_date: "2017-11-06",
            name: "Frankie Drake Mysteries",
            vote_average: 6.8,
            vote_count: 32
        },
        {
            adult: false,
            backdrop_path: "/ydDAi3xMCk7ZkRSpITaeoq4Q1Qd.jpg",
            genre_ids: [80, 18, 9648],
            id: 72748,
            origin_country: ["GB"],
            original_language: "en",
            original_name: "Strike",
            overview:
                "A war veteran turned private detective operates out of a tiny office in London’s Denmark Street. Although wounded both physically and psychologically, his unique insight and background as a military police investigator prove crucial in solving complex crimes that have baffled the police. Based on the bestselling novels written by J.K. Rowling under the pseudonym Robert Galbraith.",
            popularity: 59.651,
            poster_path: "/oPTJfwuMLz6Lr3suGK4584MAJAC.jpg",
            first_air_date: "2017-08-27",
            name: "Strike",
            vote_average: 7.104,
            vote_count: 149
        },
        {
            adult: false,
            backdrop_path: "/6OQHKY4G9wAGwX2riJEzPeGlIu3.jpg",
            genre_ids: [80, 18, 9648],
            id: 100010,
            origin_country: ["US"],
            original_language: "en",
            original_name: "Big Sky",
            overview:
                "Private detective Cassie Dewell partners with ex-cop Jenny Hoyt on a search for two sisters who have been kidnapped by a truck driver on a remote highway in Montana. When they discover that these are not the only girls who have disappeared in the area, they must race against the clock to stop the perpetrator before another woman is taken.",
            popularity: 317.432,
            poster_path: "/4CUK42x0TvcWvuRXfjAFQlCeRdf.jpg",
            first_air_date: "2020-11-17",
            name: "Big Sky",
            vote_average: 7.362,
            vote_count: 232
        }
    ],
    total_pages: 528,
    total_results: 10547
}
